config/routes.rb
Rails.application.routes.draw do
  get 'item/index'
  get 'mypage/index'
  get 'item/:id', to: 'item#show'
  get 'cart', to: 'cart#show'
  post 'cart', to: 'cart#create'
  devise_for :ecs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :ec

  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item

  belongs_to :cart
end

app/models/ec.rb
class Ec < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def show
    cart = Cart.find_or_create_by(ec: current_ec)
    @cart_items = CartItem.where(cart: cart)
  end

  def create
    cart = Cart.find_or_create_by(ec: current_ec)
           CartItem.create(item: Item.find(params[:item_id]), cart: cart, number: params[:number])
           

      redirect_to cart_path
  end




end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  def index
key_word = params[:name]
    if key_word.blank?
       @items = Item.all
    else
       @items = Item.where("(name like ?) OR (description like ?)", "%#{key_word}%", "%#{key_word}%")
    end
  end
  def show
     @items = Item.find_by(id: params[:id])

  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController

  before_action :authenticate_ec!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/views/cart/show.html.erb
<h1>Cart index</h1>
<% @cart_items.each do |cart_item| %>

<div>
  <%= link_to(cart_item.item.name, "/item/#{cart_item.item.id}") %>
  <p><%= cart_item.item.price.to_i %></p>
    <p><%= cart_item.number %></p>
  <%= image_tag url_for(cart_item.item.image), width: "200px" %>
</div>
<% end %>

app/views/item/cart_index.erb
<h1>Cart index</h1>

app/views/item/index.html.erb
<h1>Items</h1>

<%= form_tag(item_index_path, method: "get") do %>
<%= text_field_tag :name, params[:name] %>
 <%#= select_tag 'page[name]', options_for_select([["Railsの基礎", "rails_base"], ["Rubyの基礎", "ruby_base"]]) %>
<%= submit_tag "検索" %>
<% end %>

<% @items.each do |item| %>

<div>
  <%= link_to(item.name, "/item/#{item.id}") %>
  <p><%= item.price.to_i %></p>
  <%= image_tag url_for(item.image), width: "200px" %>
</div>
<% end %>

app/views/item/show.html.erb
<p>Item description</p>
<P><%= image_tag url_for(@items.image), width: "200px" %></p>
<p><%= form_tag(cart_path, method: "post") do %>
  <%= hidden_field_tag "item_id", @items.id %>
  <select name="number">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
    </select>
<%= submit_tag "カートに入れる" %>
<% end %>
</p>
<%= @items.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mypage/index.html.erb
<h1>Mypage</h1>

<%= link_to('Logout', destroy_ec_session_path, method: :delete) %> 